#!/bin/bash

SINKS=$(pactl list short sinks)
#SINK_COUNT=$(echo "$SINKS" | wc -l)

#DEFAULT_SINK=$(pactl info | sed -En 's/Default Sink: (.*)/\1/p')
#DEFAULT_SINK_INDEX=$(echo "$SINKS" | grep -n "$DEFAULT_SINK" | egrep -o '^[0-9]+')

#NEW_SINK_INDEX=$((DEFAULT_SINK_INDEX % $SINK_COUNT + 1))
CHOICE=$(echo "$SINKS" | awk '{ print $2 }' | awk -F '.' '{ print $2 }' | rofi -dmenu -i -p "")
NEW_SINK=$(echo "$SINKS" | grep "$CHOICE" | awk '{ print $1 }')
echo "New Sink is $NEW_SINK"
# Set next sink as the default sink
pactl set-default-sink "$NEW_SINK"

# Forward all playing audio (sink inputs) to the new sink
SINK_INPUTS=($(pactl list short sink-inputs | grep -E -o '^[0-9]+'))
for SINK_INPUT in ${SINK_INPUTS[*]}; do 
echo "pactl move-sink-input $SINK_INPUT $NEW_SINK";
pactl move-sink-input $SINK_INPUT $NEW_SINK; 
done
